# packages and sources

library(autoNumCaptions)
library(betareg)
library(broom)
library(broom.mixed)
library(caret)
library(cowplot)
library(cplm)
library(data.table)
library(decontam)
library(doParallel)
library(foreach)
library(ggbeeswarm)
library(ggh4x)
library(ggnewscale)
library(ggrepel)
library(helpers)
library(igraph)
library(knitr)
library(lmtest)
library(magrittr)
library(mediation)
library(parsnip)
library(phyloseq)
library(phyloseqCompanion)
library(picante)
library(pracma)
library(pROC)
library(ranger)
library(RColorBrewer)
library(rcompanion)
library(readxl)
library(recipes)
library(rsample)
library(RedoControl)
library(SpiecEasi)
library(tidyverse)
library(tools)
library(usedist)
library(workflows)

if (!dir.exists("Saved_objects/Citations_history")) { dir.create("Saved_objects/Citations_history") }
write_bib(
  file = paste0("Saved_objects/Citations_history/package_citations_", Sys.Date(), ".bib")
)
